name: Java CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install local dependencies
      run: |
        mvn install:install-file -Dfile=./libs/gpsUtil.jar -DgroupId=com.openclassrooms.gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=./libs/TripPricer.jar -DgroupId=com.openclassrooms.tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=./libs/RewardCentral.jar -DgroupId=com.openclassrooms.rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

    - name: Compile
      run: mvn compile --batch-mode

    - name: Run tests
      run: mvn test --batch-mode

    - name: Build artifacts
      run: mvn package --batch-mode -DskipTests

